
logging:
  level:
    com.shoueb.itworld: debug
    tk:
      mybatis:
        springboot:
          mapper: debug
mapper:
  identity: MYSQL
  mappers: com.shoueb.comm.MyMapper
  not-empty: false
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.shoueb.itworld.*.model
pagehelper:
  helperDialect: mysql
  params: count=countSql
  supportMethodsArguments: true
  reasonable: false
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/itworld?serverTimezone=UTC&characterEncoding=utf-8
    username: root
  profiles:
    active: dev
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 1
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 10000